/*------------------------------------------------------*/
/*---------------------ACTIVITE 1-----------------------*/
/*------------------------------------------------------*/
SELECT USR_PSEUDO, ACT_CONTENU
FROM T_UTILISATEUR_USR
LEFT OUTER JOIN T_ACTUALITE_ACT USING (USR_ID);

SELECT USR_PSEUDO
FROM T_UTILISATEUR_USR
LEFT OUTER JOIN T_ACTUALITE_ACT USING (USR_ID)
WHERE ACT_CONTENU IS NULL;

SELECT USR_PSEUDO
FROM T_UTILISATEUR_USR
WHERE USR_ID NOT IN (SELECT USR_ID
					FROM T_ACTUALITE_ACT);

SELECT USR_PSEUDO
FROM T_UTILISATEUR_USR
EXCEPT
SELECT USR_PSEUDO
FROM T_UTILISATEUR_USR
JOIN T_ACTUALITE_ACT USING (USR_ID);