/*-------- ACTUALITES --------*/
/*--- EN TANT QUE VISITEUR ---*/

/*1*/
SELECT ACT_TITRE, ACT_CONTENU, ACT_DATE, USR_PSEUDO
FROM T_ACTUALITE_ACT
JOIN T_UTILISATEUR_USR USING (USR_ID);

/*2*/
SELECT * FROM T_ACTUALITE_ACT WHERE ACT_ID=5;

/*3*/
SELECT ACT_TITRE, ACT_CONTENU, ACT_DATE
FROM T_ACTUALITE_ACT
ORDER BY ACT_DATE DESC
LIMIT 5;

/*4*/
SELECT ACT_TITRE, ACT_CONTENU, ACT_DATE
FROM T_ACTUALITE_ACT
WHERE ACT_CONTENU LIKE '%nouveau%';

/*5*/
SELECT ACT_TITRE, ACT_CONTENU, ACT_DATE, USR_ID
FROM T_ACTUALITE_ACT
WHERE ACT_DATE LIKE '%2022-10-28%';


/*-------- MATCHS ----------*/
/*--- EN TANT QUE JOUEUR ---*/
/*1*/
SELECT MAT_CODE FROM T_MATCH_MAT WHERE MAT_CODE='QUI3USR6';

/*2*/
INSERT INTO T_JOUEUR_JOU VALUES
	(NULL, 8, 'valentin', NULL);

/*3*/
SELECT JOU_PSEUDO
FROM T_JOUEUR_JOU
JOIN T_MATCH_MAT USING (MAT_ID)
WHERE MAT_ID=8 AND JOU_PSEUDO='valentin';

/*4*/
SELECT QST_INTITULE, REP_TEXTE
FROM T_MATCH_MAT
JOIN T_QUIZ_QUI USING (QUI_ID)
RIGHT OUTER JOIN T_QUESTION_QST USING (QUI_ID)
RIGHT OUTER JOIN T_REPONSE_REP USING (QST_ID)
WHERE MAT_ID=8;


/*--------------- ACTUALITES -----------------*/
/*--- EN TANT QUE FORMATEUR/ADMINISTRATEUR ---*/
/*1*/
SELECT ACT_ID, ACT_TITRE, ACT_CONTENU, ACT_DATE, USR_ID
FROM T_UTILISATEUR_USR
LEFT OUTER JOIN T_ACTUALITE_ACT USING (USR_ID)
WHERE USR_ID=1;

/*---------------- PROFILS -------------------*/
/*--- EN TANT QUE FORMATEUR/ADMINISTRATEUR ---*/
/*1*/
SELECT * 
FROM T_PROFIL_PRO
RIGHT OUTER JOIN T_UTILISATEUR_USR USING (USR_ID);

/*2*/
SELECT * 
FROM T_PROFIL_PRO
RIGHT OUTER JOIN T_UTILISATEUR_USR USING (USR_ID)
WHERE USR_ROLE='F';

SELECT * 
FROM T_PROFIL_PRO
RIGHT OUTER JOIN T_UTILISATEUR_USR USING (USR_ID)
WHERE USR_ROLE='A';

/*3*/
SELECT USR_PSEUDO, USR_MDP
FROM T_UTILISATEUR_USR
WHERE USR_PSEUDO='LMts' AND USR_MDP='mdp';

/*4*/
SELECT * 
FROM T_PROFIL_PRO
RIGHT OUTER JOIN T_UTILISATEUR_USR USING (USR_ID)
WHERE USR_PSEUDO='LMts' AND USR_MDP='mdp';

/*5*/
SELECT USR_PSEUDO, USR_MDP, USR_ETAT
FROM T_UTILISATEUR_USR;


/*---------- QUIZ -------------*/
/*--- EN TANT QUE FORMATEUR ---*/
/*1*/
SELECT *
FROM T_QUIZ_QUI
JOIN T_QUESTION_QST USING (QUI_ID)
LEFT OUTER JOIN T_REPONSE_REP USING (QST_ID)
WHERE QUI_ID=3;

/*2*/
SELECT COUNT(*) AS NbrQst
FROM T_QUESTION_QST
WHERE QUI_ID=4;


/*--------- MATCH -------------*/
/*--- EN TANT QUE FORMATEUR ---*/
/*1*/
SELECT *
FROM T_MATCH_MAT
JOIN T_QUIZ_QUI USING (QUI_ID)
JOIN T_QUESTION_QST USING (QUI_ID)
JOIN T_REPONSE_REP USING (QST_ID)
WHERE MAT_CODE='USR6QUI1';

/*2*/
SELECT COUNT(*) AS NbrJoueurs
FROM T_JOUEUR_JOU
WHERE MAT_ID=2;

/*3*/
SELECT AVG(JOU_SCORE)
FROM T_JOUEUR_JOU
WHERE MAT_ID=6;

/*4*/
SELECT JOU_PSEUDO, JOU_SCORE
FROM T_JOUEUR_JOU
WHERE MAT_ID=1;

/*5*/
SELECT *
FROM T_MATCH_MAT
JOIN T_UTILISATEUR_USR USING (USR_ID)
WHERE USR_PSEUDO='Anna' AND USR_MDP='mdp_anna';

/*6*/
SELECT *
FROM T_MATCH_MAT
WHERE QUI_ID=3;
